language: go

go:
  - 1.7.5
  - 1.8.3
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_script:
  - GO_FILES=$(find . -iname '*.go' | grep -v /vendor/)
  - PKGS=$(go list ./... | grep -v /vendor/)

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race $PKGS
  - go vet $PKGS
